apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-data-2  # Уникальное имя для второго сервера
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi  # Размер тома (можно увеличить для больших миров)