apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-2
  template:
    metadata:
      labels:
        app: minecraft-2
    spec:
      containers:
      - name: minecraft
        image: itzg/minecraft-server:latest
        env:
        - name: EULA
          value: "TRUE"
        - name: TYPE
          value: "FTBA"
        - name: FTB_MODPACK_ID
          value: "25"  # Updated Pack ID
        - name: FTB_MODPACK_VERSION_ID
          value: "123"  # Updated Version ID
        - name: VERSION
          value: "1.12.2"  # Adjust if your modpack uses different version
        - name: MEMORY
          value: "4G"  # Recommended minimum for most FTB packs
        - name: MAX_MEMORY
          value: "6G"
        - name: JVM_XX_OPTS
          value: "-XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=100 -XX:MaxRAMPercentage=80"
        - name: SERVER_NAME
          value: "FTB Modpack Server"
        - name: MOTD
          value: "Welcome to FTB Modpack!"
        - name: ENABLE_AUTOPAUSE
          value: "true"
        ports:
        - containerPort: 25565
          name: minecraft
        volumeMounts:
        - mountPath: /data
          name: minecraft-data
        resources:
          requests:
            memory: "4Gi"
            cpu: "1"
          limits:
            memory: "6Gi"
            cpu: "2"
      volumes:
      - name: minecraft-data
        persistentVolumeClaim:
          claimName: minecraft-data-2