apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-2
  template:
    metadata:
      labels:
        app: minecraft-2
    spec:
      containers:
      - name: minecraft
        image: itzg/minecraft-server:latest
        env:
        - name: EULA
          value: "TRUE"
        - name: TYPE
          value: "FTBA"  # Для FTB-модпаков
        - name: FTB_MODPACK_ID  # Обязательный параметр для FTBA
          value: "67"  # ID модпака SkyFactory 3
        - name: FTB_MODPACK_VERSION_ID
          value: "790"  # ID версии модпака
        - name: VERSION
          value: "1.12.2"
        - name: MEMORY
          value: "3G"
        - name: MAX_MEMORY
          value: "4G"
        - name: JVM_XX_OPTS
          value: "-XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=100"
        - name: SERVER_NAME
          value: "SkyFactory 3"
        - name: MOTD
          value: "Добро пожаловать на SkyFactory 3!"
        ports:
        - containerPort: 25565
          name: minecraft
        volumeMounts:
        - mountPath: /data
          name: minecraft-data
      volumes:
      - name: minecraft-data
        persistentVolumeClaim:
          claimName: minecraft-data-2