apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-2
  template:
    metadata:
      labels:
        app: minecraft-2
    spec:
      containers:
      - name: minecraft
        image: itzg/minecraft-server:latest
        env:
        - name: EULA
          value: "TRUE"
        - name: TYPE
          value: "FTBA"  # Исправлено с CURSEFORGE на FTBA для FTB-модпаков
        - name: FTB_SERVER_MOD  # Ключевое изменение: заменяем MODPACK_URL
          value: "https://api.modpacks.ch/public/modpack/67/790/server/linux"  # SkyFactory 3
        - name: VERSION
          value: "1.12.2"
        - name: MEMORY
          value: "3G"  # Увеличено с 2G для стабильности
        - name: MAX_MEMORY
          value: "4G"
        - name: JVM_XX_OPTS
          value: "-XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=100 -XX:MaxRAMPercentage=80"
        - name: SERVER_NAME
          value: "SkyFactory 3"
        - name: MOTD
          value: "Добро пожаловать на SkyFactory 3!"
        - name: ENABLE_AUTOPAUSE
          value: "true"  # Автопауза при отсутствии игроков
        ports:
        - containerPort: 25565
          name: minecraft
        volumeMounts:
        - mountPath: /data
          name: minecraft-data
        resources:
          requests:
            memory: "3Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "2"
      volumes:
      - name: minecraft-data
        persistentVolumeClaim:
          claimName: minecraft-data-2