apiVersion: v1
kind: Service
metadata:
  name: minecraft-service
  namespace: minecraft
spec:
  type: NodePort
  selector:
    app: minecraft
  ports:
    - protocol: TCP
      port: 25565
      targetPort: 25565
      nodePort: 30000 # Можно указать конкретный порт или оставить пустым для автоматического выбора