apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minecraft-server-2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Cellofworld/minecraft_server.git' # Замените на ваш репозиторий
    path: minecraft-plugin # Путь к манифестам в репозитории
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: minecraft
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

    